spring.application.name=ProjetoAcessibilidade
valhalla.api.url=${VALHALLA_URL:http://localhost:8002}


spring.data.mongodb.uri=mongodb+srv://dbUser:UPctTugP5tM3EReA@cluster0.r7x2dyq.mongodb.net/projeto_acessibilidade?retryWrites=true&w=majority&appName=Cluster0
