spring.application.name=ProjetoAcessibilidade
valhalla.api.url=${VALHALLA_URL:http://localhost:8002}


spring.data.mongodb.uri=mongodb+srv://dbUser:Ola*1401@@cluster0.exatear.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
